#############################################################################
# Makefile for building: Sip_Stack
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  Sip_Stack.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Sip_Stack.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-util \
		sub-sip \
		sub-net_util \
		sub-crypto \
		sub-mini_sip \
		sub-stun \
		sub-ilbc \
		sub-mini_stun \
		sub-game \
		sub-mikey \
		sub-main


sub-util-qmake_all:  FORCE
	@test -d util/ || mkdir -p util/
	cd util/ && $(QMAKE) /home/whg/project/Sip_Stack/util/util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd util/ && $(MAKE) -f Makefile qmake_all
sub-util: FORCE
	@test -d util/ || mkdir -p util/
	cd util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/util/util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-util-make_first: FORCE
	@test -d util/ || mkdir -p util/
	cd util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/util/util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-util-all: FORCE
	@test -d util/ || mkdir -p util/
	cd util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/util/util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-util-clean: FORCE
	@test -d util/ || mkdir -p util/
	cd util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/util/util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-util-distclean: FORCE
	@test -d util/ || mkdir -p util/
	cd util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/util/util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-util-install_subtargets: FORCE
	@test -d util/ || mkdir -p util/
	cd util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/util/util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-util-uninstall_subtargets: FORCE
	@test -d util/ || mkdir -p util/
	cd util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/util/util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-sip-qmake_all:  FORCE
	@test -d sip/ || mkdir -p sip/
	cd sip/ && $(QMAKE) /home/whg/project/Sip_Stack/sip/sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd sip/ && $(MAKE) -f Makefile qmake_all
sub-sip: FORCE
	@test -d sip/ || mkdir -p sip/
	cd sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/sip/sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-sip-make_first: FORCE
	@test -d sip/ || mkdir -p sip/
	cd sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/sip/sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-sip-all: FORCE
	@test -d sip/ || mkdir -p sip/
	cd sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/sip/sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-sip-clean: FORCE
	@test -d sip/ || mkdir -p sip/
	cd sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/sip/sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-sip-distclean: FORCE
	@test -d sip/ || mkdir -p sip/
	cd sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/sip/sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-sip-install_subtargets: FORCE
	@test -d sip/ || mkdir -p sip/
	cd sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/sip/sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-sip-uninstall_subtargets: FORCE
	@test -d sip/ || mkdir -p sip/
	cd sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/sip/sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-net_util-qmake_all:  FORCE
	@test -d net_util/ || mkdir -p net_util/
	cd net_util/ && $(QMAKE) /home/whg/project/Sip_Stack/net_util/net_util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd net_util/ && $(MAKE) -f Makefile qmake_all
sub-net_util: FORCE
	@test -d net_util/ || mkdir -p net_util/
	cd net_util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/net_util/net_util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-net_util-make_first: FORCE
	@test -d net_util/ || mkdir -p net_util/
	cd net_util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/net_util/net_util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-net_util-all: FORCE
	@test -d net_util/ || mkdir -p net_util/
	cd net_util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/net_util/net_util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-net_util-clean: FORCE
	@test -d net_util/ || mkdir -p net_util/
	cd net_util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/net_util/net_util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-net_util-distclean: FORCE
	@test -d net_util/ || mkdir -p net_util/
	cd net_util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/net_util/net_util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-net_util-install_subtargets: FORCE
	@test -d net_util/ || mkdir -p net_util/
	cd net_util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/net_util/net_util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-net_util-uninstall_subtargets: FORCE
	@test -d net_util/ || mkdir -p net_util/
	cd net_util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/net_util/net_util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-crypto-qmake_all:  FORCE
	@test -d crypto/ || mkdir -p crypto/
	cd crypto/ && $(QMAKE) /home/whg/project/Sip_Stack/crypto/crypto.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd crypto/ && $(MAKE) -f Makefile qmake_all
sub-crypto: FORCE
	@test -d crypto/ || mkdir -p crypto/
	cd crypto/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/crypto/crypto.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-crypto-make_first: FORCE
	@test -d crypto/ || mkdir -p crypto/
	cd crypto/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/crypto/crypto.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-crypto-all: FORCE
	@test -d crypto/ || mkdir -p crypto/
	cd crypto/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/crypto/crypto.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-crypto-clean: FORCE
	@test -d crypto/ || mkdir -p crypto/
	cd crypto/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/crypto/crypto.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-crypto-distclean: FORCE
	@test -d crypto/ || mkdir -p crypto/
	cd crypto/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/crypto/crypto.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-crypto-install_subtargets: FORCE
	@test -d crypto/ || mkdir -p crypto/
	cd crypto/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/crypto/crypto.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-crypto-uninstall_subtargets: FORCE
	@test -d crypto/ || mkdir -p crypto/
	cd crypto/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/crypto/crypto.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-mini_sip-qmake_all:  FORCE
	@test -d mini_sip/ || mkdir -p mini_sip/
	cd mini_sip/ && $(QMAKE) /home/whg/project/Sip_Stack/mini_sip/mini_sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd mini_sip/ && $(MAKE) -f Makefile qmake_all
sub-mini_sip: FORCE
	@test -d mini_sip/ || mkdir -p mini_sip/
	cd mini_sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_sip/mini_sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-mini_sip-make_first: FORCE
	@test -d mini_sip/ || mkdir -p mini_sip/
	cd mini_sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_sip/mini_sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-mini_sip-all: FORCE
	@test -d mini_sip/ || mkdir -p mini_sip/
	cd mini_sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_sip/mini_sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-mini_sip-clean: FORCE
	@test -d mini_sip/ || mkdir -p mini_sip/
	cd mini_sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_sip/mini_sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-mini_sip-distclean: FORCE
	@test -d mini_sip/ || mkdir -p mini_sip/
	cd mini_sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_sip/mini_sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-mini_sip-install_subtargets: FORCE
	@test -d mini_sip/ || mkdir -p mini_sip/
	cd mini_sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_sip/mini_sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-mini_sip-uninstall_subtargets: FORCE
	@test -d mini_sip/ || mkdir -p mini_sip/
	cd mini_sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_sip/mini_sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-stun-qmake_all:  FORCE
	@test -d stun/ || mkdir -p stun/
	cd stun/ && $(QMAKE) /home/whg/project/Sip_Stack/stun/stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd stun/ && $(MAKE) -f Makefile qmake_all
sub-stun: FORCE
	@test -d stun/ || mkdir -p stun/
	cd stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/stun/stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-stun-make_first: FORCE
	@test -d stun/ || mkdir -p stun/
	cd stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/stun/stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-stun-all: FORCE
	@test -d stun/ || mkdir -p stun/
	cd stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/stun/stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-stun-clean: FORCE
	@test -d stun/ || mkdir -p stun/
	cd stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/stun/stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-stun-distclean: FORCE
	@test -d stun/ || mkdir -p stun/
	cd stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/stun/stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-stun-install_subtargets: FORCE
	@test -d stun/ || mkdir -p stun/
	cd stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/stun/stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-stun-uninstall_subtargets: FORCE
	@test -d stun/ || mkdir -p stun/
	cd stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/stun/stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ilbc-qmake_all:  FORCE
	@test -d ilbc/ || mkdir -p ilbc/
	cd ilbc/ && $(QMAKE) /home/whg/project/Sip_Stack/ilbc/ilbc.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd ilbc/ && $(MAKE) -f Makefile qmake_all
sub-ilbc: FORCE
	@test -d ilbc/ || mkdir -p ilbc/
	cd ilbc/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/ilbc/ilbc.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-ilbc-make_first: FORCE
	@test -d ilbc/ || mkdir -p ilbc/
	cd ilbc/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/ilbc/ilbc.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-ilbc-all: FORCE
	@test -d ilbc/ || mkdir -p ilbc/
	cd ilbc/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/ilbc/ilbc.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-ilbc-clean: FORCE
	@test -d ilbc/ || mkdir -p ilbc/
	cd ilbc/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/ilbc/ilbc.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-ilbc-distclean: FORCE
	@test -d ilbc/ || mkdir -p ilbc/
	cd ilbc/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/ilbc/ilbc.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ilbc-install_subtargets: FORCE
	@test -d ilbc/ || mkdir -p ilbc/
	cd ilbc/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/ilbc/ilbc.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-ilbc-uninstall_subtargets: FORCE
	@test -d ilbc/ || mkdir -p ilbc/
	cd ilbc/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/ilbc/ilbc.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-mini_stun-qmake_all:  FORCE
	@test -d mini_stun/ || mkdir -p mini_stun/
	cd mini_stun/ && $(QMAKE) /home/whg/project/Sip_Stack/mini_stun/mini_stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd mini_stun/ && $(MAKE) -f Makefile qmake_all
sub-mini_stun: FORCE
	@test -d mini_stun/ || mkdir -p mini_stun/
	cd mini_stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_stun/mini_stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-mini_stun-make_first: FORCE
	@test -d mini_stun/ || mkdir -p mini_stun/
	cd mini_stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_stun/mini_stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-mini_stun-all: FORCE
	@test -d mini_stun/ || mkdir -p mini_stun/
	cd mini_stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_stun/mini_stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-mini_stun-clean: FORCE
	@test -d mini_stun/ || mkdir -p mini_stun/
	cd mini_stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_stun/mini_stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-mini_stun-distclean: FORCE
	@test -d mini_stun/ || mkdir -p mini_stun/
	cd mini_stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_stun/mini_stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-mini_stun-install_subtargets: FORCE
	@test -d mini_stun/ || mkdir -p mini_stun/
	cd mini_stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_stun/mini_stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-mini_stun-uninstall_subtargets: FORCE
	@test -d mini_stun/ || mkdir -p mini_stun/
	cd mini_stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_stun/mini_stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-game-qmake_all:  FORCE
	@test -d game/ || mkdir -p game/
	cd game/ && $(QMAKE) /home/whg/project/Sip_Stack/game/game.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd game/ && $(MAKE) -f Makefile qmake_all
sub-game: FORCE
	@test -d game/ || mkdir -p game/
	cd game/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/game/game.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-game-make_first: FORCE
	@test -d game/ || mkdir -p game/
	cd game/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/game/game.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-game-all: FORCE
	@test -d game/ || mkdir -p game/
	cd game/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/game/game.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-game-clean: FORCE
	@test -d game/ || mkdir -p game/
	cd game/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/game/game.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-game-distclean: FORCE
	@test -d game/ || mkdir -p game/
	cd game/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/game/game.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-game-install_subtargets: FORCE
	@test -d game/ || mkdir -p game/
	cd game/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/game/game.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-game-uninstall_subtargets: FORCE
	@test -d game/ || mkdir -p game/
	cd game/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/game/game.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-mikey-qmake_all:  FORCE
	@test -d mikey/ || mkdir -p mikey/
	cd mikey/ && $(QMAKE) /home/whg/project/Sip_Stack/mikey/mikey.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd mikey/ && $(MAKE) -f Makefile qmake_all
sub-mikey: FORCE
	@test -d mikey/ || mkdir -p mikey/
	cd mikey/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mikey/mikey.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-mikey-make_first: FORCE
	@test -d mikey/ || mkdir -p mikey/
	cd mikey/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mikey/mikey.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-mikey-all: FORCE
	@test -d mikey/ || mkdir -p mikey/
	cd mikey/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mikey/mikey.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-mikey-clean: FORCE
	@test -d mikey/ || mkdir -p mikey/
	cd mikey/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mikey/mikey.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-mikey-distclean: FORCE
	@test -d mikey/ || mkdir -p mikey/
	cd mikey/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mikey/mikey.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-mikey-install_subtargets: FORCE
	@test -d mikey/ || mkdir -p mikey/
	cd mikey/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mikey/mikey.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-mikey-uninstall_subtargets: FORCE
	@test -d mikey/ || mkdir -p mikey/
	cd mikey/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mikey/mikey.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-main-qmake_all:  FORCE
	@test -d main/ || mkdir -p main/
	cd main/ && $(QMAKE) /home/whg/project/Sip_Stack/main/main.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd main/ && $(MAKE) -f Makefile qmake_all
sub-main: FORCE
	@test -d main/ || mkdir -p main/
	cd main/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/main/main.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-main-make_first: FORCE
	@test -d main/ || mkdir -p main/
	cd main/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/main/main.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-main-all: FORCE
	@test -d main/ || mkdir -p main/
	cd main/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/main/main.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-main-clean: FORCE
	@test -d main/ || mkdir -p main/
	cd main/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/main/main.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-main-distclean: FORCE
	@test -d main/ || mkdir -p main/
	cd main/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/main/main.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-main-install_subtargets: FORCE
	@test -d main/ || mkdir -p main/
	cd main/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/main/main.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-main-uninstall_subtargets: FORCE
	@test -d main/ || mkdir -p main/
	cd main/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/main/main.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: Sip_Stack.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/declarative_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Sip_Stack.pro
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Sip_Stack.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/declarative_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Sip_Stack.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Sip_Stack.pro

qmake_all: sub-util-qmake_all sub-sip-qmake_all sub-net_util-qmake_all sub-crypto-qmake_all sub-mini_sip-qmake_all sub-stun-qmake_all sub-ilbc-qmake_all sub-mini_stun-qmake_all sub-game-qmake_all sub-mikey-qmake_all sub-main-qmake_all FORCE

make_first: sub-util-make_first sub-sip-make_first sub-net_util-make_first sub-crypto-make_first sub-mini_sip-make_first sub-stun-make_first sub-ilbc-make_first sub-mini_stun-make_first sub-game-make_first sub-mikey-make_first sub-main-make_first FORCE
all: sub-util-all sub-sip-all sub-net_util-all sub-crypto-all sub-mini_sip-all sub-stun-all sub-ilbc-all sub-mini_stun-all sub-game-all sub-mikey-all sub-main-all FORCE
clean: sub-util-clean sub-sip-clean sub-net_util-clean sub-crypto-clean sub-mini_sip-clean sub-stun-clean sub-ilbc-clean sub-mini_stun-clean sub-game-clean sub-mikey-clean sub-main-clean FORCE
distclean: sub-util-distclean sub-sip-distclean sub-net_util-distclean sub-crypto-distclean sub-mini_sip-distclean sub-stun-distclean sub-ilbc-distclean sub-mini_stun-distclean sub-game-distclean sub-mikey-distclean sub-main-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-util-install_subtargets sub-sip-install_subtargets sub-net_util-install_subtargets sub-crypto-install_subtargets sub-mini_sip-install_subtargets sub-stun-install_subtargets sub-ilbc-install_subtargets sub-mini_stun-install_subtargets sub-game-install_subtargets sub-mikey-install_subtargets sub-main-install_subtargets FORCE
uninstall_subtargets: sub-util-uninstall_subtargets sub-sip-uninstall_subtargets sub-net_util-uninstall_subtargets sub-crypto-uninstall_subtargets sub-mini_sip-uninstall_subtargets sub-stun-uninstall_subtargets sub-ilbc-uninstall_subtargets sub-mini_stun-uninstall_subtargets sub-game-uninstall_subtargets sub-mikey-uninstall_subtargets sub-main-uninstall_subtargets FORCE

sub-util-check:
	@test -d util/ || mkdir -p util/
	cd util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/util/util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-sip-check:
	@test -d sip/ || mkdir -p sip/
	cd sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/sip/sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-net_util-check:
	@test -d net_util/ || mkdir -p net_util/
	cd net_util/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/net_util/net_util.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-crypto-check:
	@test -d crypto/ || mkdir -p crypto/
	cd crypto/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/crypto/crypto.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-mini_sip-check:
	@test -d mini_sip/ || mkdir -p mini_sip/
	cd mini_sip/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_sip/mini_sip.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-stun-check:
	@test -d stun/ || mkdir -p stun/
	cd stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/stun/stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-ilbc-check:
	@test -d ilbc/ || mkdir -p ilbc/
	cd ilbc/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/ilbc/ilbc.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-mini_stun-check:
	@test -d mini_stun/ || mkdir -p mini_stun/
	cd mini_stun/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mini_stun/mini_stun.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-game-check:
	@test -d game/ || mkdir -p game/
	cd game/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/game/game.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-mikey-check:
	@test -d mikey/ || mkdir -p mikey/
	cd mikey/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/mikey/mikey.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-main-check:
	@test -d main/ || mkdir -p main/
	cd main/ && ( test -e Makefile || $(QMAKE) /home/whg/project/Sip_Stack/main/main.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-util-check sub-sip-check sub-net_util-check sub-crypto-check sub-mini_sip-check sub-stun-check sub-ilbc-check sub-mini_stun-check sub-game-check sub-mikey-check sub-main-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

